[2024-05-30T07:54:56.649+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:54:56.699+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: training_models.choose_best_model scheduled__2024-05-29T00:00:00+00:00 [queued]>
[2024-05-30T07:54:56.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: training_models.choose_best_model scheduled__2024-05-29T00:00:00+00:00 [queued]>
[2024-05-30T07:54:56.722+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:54:56.760+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-29 00:00:00+00:00
[2024-05-30T07:54:56.774+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3300) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-30T07:54:56.778+0000] {standard_task_runner.py:63} INFO - Started process 3308 to run task
[2024-05-30T07:54:56.781+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'training_models', 'choose_best_model', 'scheduled__2024-05-29T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/training_models.py', '--cfg-path', '/tmp/tmpj7eumzht']
[2024-05-30T07:54:56.787+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask choose_best_model
[2024-05-30T07:54:56.909+0000] {task_command.py:426} INFO - Running <TaskInstance: training_models.choose_best_model scheduled__2024-05-29T00:00:00+00:00 [running]> on host abdc8a9dc09e
[2024-05-30T07:54:57.159+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='training_models' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-29T00:00:00+00:00'
[2024-05-30T07:54:57.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:54:57.166+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-30T07:54:57.189+0000] {python.py:237} INFO - Done. Returned value was: accurate
[2024-05-30T07:54:57.190+0000] {branch.py:36} INFO - Branch into accurate
[2024-05-30T07:54:57.191+0000] {skipmixin.py:178} INFO - Following branch accurate
[2024-05-30T07:54:57.248+0000] {skipmixin.py:246} INFO - Skipping tasks [('inaccurate', -1)]
[2024-05-30T07:54:57.321+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:54:57.405+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=training_models, task_id=choose_best_model, run_id=scheduled__2024-05-29T00:00:00+00:00, execution_date=20240529T000000, start_date=20240530T075456, end_date=20240530T075457
[2024-05-30T07:54:57.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:54:57.556+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:54:57.591+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
