[2024-05-29T15:49:00.092+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T15:49:00.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.choose_best_model manual__2024-05-29T15:48:52.681081+00:00 [queued]>
[2024-05-29T15:49:00.134+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.choose_best_model manual__2024-05-29T15:48:52.681081+00:00 [queued]>
[2024-05-29T15:49:00.136+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T15:49:00.155+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-29 15:48:52.681081+00:00
[2024-05-29T15:49:00.164+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=864) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T15:49:00.166+0000] {standard_task_runner.py:63} INFO - Started process 866 to run task
[2024-05-29T15:49:00.166+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'choose_best_model', 'manual__2024-05-29T15:48:52.681081+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp98_7g34g']
[2024-05-29T15:49:00.169+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask choose_best_model
[2024-05-29T15:49:00.230+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.choose_best_model manual__2024-05-29T15:48:52.681081+00:00 [running]> on host abdc8a9dc09e
[2024-05-29T15:49:00.361+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T15:48:52.681081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T15:48:52.681081+00:00'
[2024-05-29T15:49:00.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T15:49:00.364+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-29T15:49:00.382+0000] {python.py:237} INFO - Done. Returned value was: inaccurate
[2024-05-29T15:49:00.383+0000] {branch.py:36} INFO - Branch into inaccurate
[2024-05-29T15:49:00.384+0000] {skipmixin.py:178} INFO - Following branch inaccurate
[2024-05-29T15:49:00.409+0000] {skipmixin.py:246} INFO - Skipping tasks [('accurate', -1)]
[2024-05-29T15:49:00.443+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T15:49:00.472+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=choose_best_model, run_id=manual__2024-05-29T15:48:52.681081+00:00, execution_date=20240529T154852, start_date=20240529T154900, end_date=20240529T154900
[2024-05-29T15:49:00.502+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T15:49:00.546+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-29T15:49:00.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
